#create_property iob port -type string
set_property IOB TRUE [all_inputs]
set_property IOB TRUE [all_outputs]


set_property IOSTANDARD LVCMOS25 [get_ports drs_denable_o]
set_property IOSTANDARD LVCMOS25 [get_ports drs_dtap_i]
set_property IOSTANDARD LVCMOS25 [get_ports drs_dwrite_o]
set_property IOSTANDARD LVCMOS25 [get_ports drs_plllock_i]
set_property IOSTANDARD LVCMOS25 [get_ports drs_nreset_o]
set_property IOSTANDARD LVCMOS25 [get_ports drs_rsrload_o]
set_property IOSTANDARD LVCMOS25 [get_ports drs_srclk_o]
set_property IOSTANDARD LVCMOS25 [get_ports drs_srin_o]
set_property IOSTANDARD LVCMOS25 [get_ports drs_srout_i]
#set_property IOSTANDARD  LVCMOS25 [get_ports drs_wrsin_o]
#set_property IOSTANDARD  LVCMOS25 [get_ports drs_wsrout_i]

set_property IOSTANDARD LVCMOS25 [get_ports {adc_data_i[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {adc_data_i[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {adc_data_i[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {adc_data_i[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {adc_data_i[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {adc_data_i[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {adc_data_i[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {adc_data_i[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {adc_data_i[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {adc_data_i[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {adc_data_i[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {adc_data_i[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {adc_data_i[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {adc_data_i[13]}]

set_property IOSTANDARD LVCMOS25 [get_ports {drs_addr_o[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {drs_addr_o[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {drs_addr_o[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {drs_addr_o[3]}]

set_property IOSTANDARD LVDS_25 [get_ports {trigger_i_p}]
set_property IOSTANDARD LVDS_25 [get_ports {trigger_i_n}]

set_property IOSTANDARD LVDS_25 [get_ports {gpio_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_n[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_n[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_n[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_n[10]}]

set_property IOSTANDARD LVDS_25 [get_ports {gpio_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_p[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_p[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {gpio_p[10]}]

set_property IOSTANDARD LVDS_25 [get_ports clock_i_n]
set_property IOSTANDARD LVDS_25 [get_ports clock_i_p]

# need to correct this
set_property PACKAGE_PIN L16 [get_ports {trigger_i_p}]
set_property PACKAGE_PIN L17 [get_ports {trigger_i_n}]

set_property PACKAGE_PIN D18 [get_ports {gpio_n[10]}]
set_property PACKAGE_PIN A20 [get_ports {gpio_n[2]}]
set_property PACKAGE_PIN B19 [get_ports {gpio_p[2]}]
set_property PACKAGE_PIN B20 [get_ports {gpio_n[1]}]
set_property PACKAGE_PIN C20 [get_ports {gpio_p[1]}]
set_property PACKAGE_PIN D19 [get_ports {gpio_p[0]}]
set_property PACKAGE_PIN D20 [get_ports {gpio_n[0]}]
set_property PACKAGE_PIN E17 [get_ports {gpio_p[10]}]
set_property PACKAGE_PIN E18 [get_ports {gpio_p[9]}]
set_property PACKAGE_PIN E19 [get_ports {gpio_n[9]}]
set_property PACKAGE_PIN F16 [get_ports {gpio_p[8]}]
set_property PACKAGE_PIN F17 [get_ports {gpio_n[8]}]
set_property PACKAGE_PIN F19 [get_ports drs_nreset_o]
set_property PACKAGE_PIN G15 [get_ports {gpio_n[3]}]
set_property PACKAGE_PIN G17 [get_ports {gpio_p[7]}]
set_property PACKAGE_PIN G18 [get_ports {gpio_n[7]}]
#set_property PACKAGE_PIN G19      [get_ports drs_wsrout_i]
set_property PACKAGE_PIN G20 [get_ports drs_srclk_o]
set_property PACKAGE_PIN H15 [get_ports {gpio_p[3]}]
set_property PACKAGE_PIN H20 [get_ports drs_srout_i]
set_property PACKAGE_PIN J16 [get_ports {gpio_n[6]}]
set_property PACKAGE_PIN J19 [get_ports drs_rsrload_o]
set_property PACKAGE_PIN J20 [get_ports drs_srin_o]
set_property PACKAGE_PIN K16 [get_ports {gpio_p[6]}]
set_property PACKAGE_PIN K17 [get_ports {gpio_p[5]}]
set_property PACKAGE_PIN K18 [get_ports {gpio_n[5]}]
set_property PACKAGE_PIN K19 [get_ports {drs_addr_o[0]}]
set_property PACKAGE_PIN L19 [get_ports {adc_data_i[9]}]
set_property PACKAGE_PIN L20 [get_ports {drs_addr_o[1]}]
set_property PACKAGE_PIN M17 [get_ports {gpio_p[4]}]
set_property PACKAGE_PIN M18 [get_ports {gpio_n[4]}]
set_property PACKAGE_PIN M19 [get_ports {adc_data_i[7]}]
set_property PACKAGE_PIN M20 [get_ports {adc_data_i[8]}]
set_property PACKAGE_PIN N15 [get_ports {adc_data_i[5]}]
set_property PACKAGE_PIN N16 [get_ports {adc_data_i[6]}]
set_property PACKAGE_PIN R16 [get_ports {drs_addr_o[2]}]
set_property PACKAGE_PIN R17 [get_ports {adc_data_i[0]}]
set_property PACKAGE_PIN R18 [get_ports drs_denable_o]
set_property PACKAGE_PIN T12 [get_ports drs_dwrite_o]
#set_property PACKAGE_PIN T17      [get_ports drs_wrsin_o]
set_property PACKAGE_PIN U12 [get_ports drs_plllock_i]
set_property PACKAGE_PIN U18 [get_ports clock_i_p]
set_property PACKAGE_PIN U19 [get_ports clock_i_n]
set_property PACKAGE_PIN V16 [get_ports drs_dtap_i]
set_property PACKAGE_PIN V15 [get_ports {adc_data_i[11]}]
set_property PACKAGE_PIN W15 [get_ports {adc_data_i[1]}]
set_property PACKAGE_PIN W16 [get_ports {drs_addr_o[3]}]
set_property PACKAGE_PIN W18 [get_ports {adc_data_i[13]}]
set_property PACKAGE_PIN W19 [get_ports {adc_data_i[4]}]
set_property PACKAGE_PIN Y16 [get_ports {adc_data_i[2]}]
set_property PACKAGE_PIN Y17 [get_ports {adc_data_i[10]}]
set_property PACKAGE_PIN Y18 [get_ports {adc_data_i[3]}]
set_property PACKAGE_PIN Y19 [get_ports {adc_data_i[12]}]



